### ISSUE TITLE
Keyboard ESC keyCode is Incorrect.

### ISSUE THREAD

**Issue by RichardMarks** [dgsprb/quick#37]
In version 2.0.1 (and possibly earlier) I have found that the keyCode mapped to ESC for the Keyboard is currently 127 which is *NOT* the ESC key. **The correct ESC keyCode is 27**. This is something that really needs to be fixed quickly. As anyone using the cdn hosted library is unable to use the ESC key in their game without jumping through hoops to manually add event listeners themselves.

**Comment by dgsprb** [comment]
This issue has been fixed on release 2.0.2. Thanks for reporting and submitting the fix, @RichardMarks!
